### ISSUE TITLE
Unselect single utxo doesn't do anything

### ISSUE THREAD

**Issue by zmoox** [NicolasDorier/BCCSpliter#1]
reproduction:
* list (suppose there's 6 utxo's)
* select all -> 6 utxo selected
* unselect a specific one
* result: still 6 utxo selected

**Comment by 0xfff** [comment]
i get the following:

```
unselect ...
BCCSpliter 1.0.0
Copyright (C) 2017 BCCSpliter

ERROR(S):
  Verb 'unselect' is not recognized.
```

**Comment by NicolasDorier** [comment]
checking now thanks.

**Comment by NicolasDorier** [comment]
Just fixed it

**Comment by NicolasDorier** [comment]
@0xfff  your 'not recognized error' should not happen with last version. If it does, verify you have not put a space before the word
