### ISSUE TITLE
An UTXO from a previous tx is still selected

### ISSUE THREAD

**Issue by 0xfff** [NicolasDorier/BCCSpliter#2]
doing `unselect txid-n` or `unselect all` display the confirmation
```
>>> unselect all
info: Main:           Unselected 2 UTXOs
```
but `list` still shows those UTXOs selected

**Comment by NicolasDorier** [comment]
fix it, indeed forgot to implement it :D

**Comment by 0xfff** [comment]
this is still happening
i `select` then `dump` then `list` and the last UTXO is still selected
i can `unselect` here to delete the UTXO's - thank you for doing that :+1: 

i guess `dump` should trigger `unselect all`

**Comment by NicolasDorier** [comment]
indeed, updated, now it will trigger unselect all after dump.
