### ISSUE TITLE
`confirm` not recognized

### ISSUE THREAD

**Issue by 0xfff** [NicolasDorier/BCCSpliter#3]
in the readme it states:

> #Wait that the dump transaction get confirmed on your favorite exchange, then unlock your coin in your Bitcoin Core wallet
> confirm 38348679e28c9df785dd0d70b5db5b45986ed107ebbe1248bb7bfbdca74cc063

but
```
>>> confirm 
BCCSpliter 1.0.0
Copyright (C) 2017 BCCSpliter

ERROR(S):
  Verb 'confirm' is not recognized.
  --help       Display this help screen.
  --version    Display version information.
```

also tried `confirm txid`

meeanwhile BTC wallet `listlockunspent` yields an empty array

**Comment by zmoox** [comment]
Nicolas removed that confirm command (and the lock/unlock stuff) in the most recent version, he just didn't update the howto yet.

**Comment by NicolasDorier** [comment]
I removed yes, it is not needed anymore as BTC transaction can't be replayed.
