### ISSUE TITLE
0 coins hd wallet

### ISSUE THREAD

**Issue by kys86468** [NicolasDorier/BCCSpliter#6]
Hello. I made dumpwallet() command and then did:
dumphd xprv9...kR 1N3...N

Result is:
info: Main:           Scanning BIP45/P2SH/1-1 path
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Scanning BIP44 (Account 0) path
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Scanning Direct path
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           No coin to dump

What's I made wrong? I'm sure that it was some btc in wallet at the moment of hard fork

**Comment by NicolasDorier** [comment]
hey, from which wallet come your xprv ?

**Comment by NicolasDorier** [comment]
I don't think you did something wrong, I might need to support your derivation scheme, but I need to know which wallet software you are using.

If it is copay, go into your wallet information and tell me the derivation scheme you are using.

**Comment by kys86468** [comment]
It's from Bitcoin Core

**Comment by kys86468** [comment]
After 1 Aug I have hundreds transactions on this wallet and I can't use dump method (from UTXO), because it shows me less BCC, that was BTC on 1 August

**Comment by NicolasDorier** [comment]
Ok got it, will support dumphd for bitcoin core, one moment.

**Comment by NicolasDorier** [comment]
I just pushed it, can you `git pull` and try again ?

**Comment by kys86468** [comment]
Hmmm

info: Main:           Scanning with strategy "BIP45/P2SH/1-1"
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Scanning with strategy "BIP44 (Account 0)"
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Scanning with strategy "Direct"
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Scanning with strategy "Bitcoin Core"
info: Main:           Found 0 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           No coin to dump

What additional info I can give you? Help, please

**Comment by NicolasDorier** [comment]
I have a bug one second

**Comment by NicolasDorier** [comment]
Ok sorry, can you try once again. There was a bug which happen only on big wallet.

**Comment by kys86468** [comment]
My wallet's size is 21Mb and about 10k addresses from dumpwallet(). 
It works (it took about 1 minute to scan), but it's not the same quantity of coins that was on 1 Aug (50 times less):

info: Main:           Scanning with strategy "Bitcoin Core"
info: Main:           Found 2 coins
info: Main:           Scanning change addresses
info: Main:           Found 0 coins
info: Main:           Dump transaction created 0100000002238cf3e7f5709c72b1bfb6cf08b9d3...7b6637e171dc50537d98df292830cc1341a67dffffffff012b92b900000000001976a914e6e4298fc77f466bc95e0294471594167f28c8d388ac00000000
info: Main:           Dump transaction ID a58f60c1224...
Are you sure to dump 0.12200000 BCash coin to 1N3q... ? (type `yes` to continue)

What additional info I can give you?

**Comment by NicolasDorier** [comment]
Again a bug, please try again. Should be good now hopefully

**Comment by kys86468** [comment]
Yessss. It works. Thanks!

**Comment by NicolasDorier** [comment]
Happy dumping!
